### ISSUE TITLE
[feat] enable customAtRules options

### ISSUE THREAD

**Issue by mpech** [mhsdesign/esbuild-plugin-lightningcss-modules#6]
It would be nice if plugin can also accept [customAtRules](https://lightningcss.dev/transforms.html#custom-at-rules)

so we can transform custom media rule in one go by using this plugin

edit: a bit out of scope,
I tested it against esbuild 0.19.5. esbuild-plugin-lightningcss-modules works :+1:

**Comment by mhsdesign** [comment]
okay feel free to create a little pr ;)

similar to https://github.com/mhsdesign/esbuild-plugin-lightningcss-modules/pull/4
